version: '3.3'

services:
  pg_denormalized:
    build: services/pg_denormalized
    volumes:
      - ./:/tmp/db
      - $HOME/bigdata/pg_denormalized:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - PGUSER=postgres
    ports:
      - 15432:5432

  pg_normalized_batch:
    build: services/pg_normalized_batch
    volumes:
      - ./:/tmp/db
      - $HOME/bigdata/pg_normalized_batch:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - PGUSER=postgres
    ports:
      - 35432:5432
